// Code generated by go-template enterprise generator at 2025-09-21T19:40:10+03:30. DO NOT EDIT.

package repositories

import (
	"context"
	"github.com/VeRJiL/go-template/internal/domain/entities"
	"github.com/VeRJiL/go-template/internal/pkg/modules"
)

// ProductRepository defines the interface for product repository
type ProductRepository interface {
	modules.Repository[entities.Product]

	// Add custom repository methods here
	FindByName(ctx context.Context, name string) (*entities.Product, error)
	FindByNameLike(ctx context.Context, pattern string) ([]*entities.Product, error)
}
