// Code generated by go-template enterprise generator at 2025-09-21T19:40:10+03:30. DO NOT EDIT.

package repositories

import (
	"context"
	"testing"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/mock"
)

// Add your repository tests here
func TestProductRepository_FindByName(t *testing.T) {
	// TODO: Implement repository tests
	t.Skip("Repository tests not yet implemented")
}
