// Code generated by go-template enterprise generator at 2025-09-21T19:40:10+03:30. DO NOT EDIT.

package entities

import (
	"testing"
	"github.com/stretchr/testify/assert"
)

func TestProduct_GetID(t *testing.T) {
	entity := &Product{ID: 1}
	assert.Equal(t, uint(1), entity.GetID())
}

func TestProduct_SetID(t *testing.T) {
	entity := &Product{}
	entity.SetID(1)
	assert.Equal(t, uint(1), entity.ID)
}

func TestProduct_GetTableName(t *testing.T) {
	entity := &Product{}
	assert.Equal(t, "products", entity.GetTableName())
}

func TestProduct_Validate(t *testing.T) {
	tests := []struct {
		name    string
		entity  Product
		wantErr bool
	}{
		{
			name:    "valid entity",
			entity:  Product{Name: "Test Product"},
			wantErr: false,
		},
		{
			name:    "invalid entity - empty name",
			entity:  Product{Name: ""},
			wantErr: true,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			err := tt.entity.Validate()
			if tt.wantErr {
				assert.Error(t, err)
			} else {
				assert.NoError(t, err)
			}
		})
	}
}
