// Code generated by go-template enterprise generator at 2025-09-21T19:40:10+03:30. DO NOT EDIT.

package services

import (
	"context"
	"github.com/VeRJiL/go-template/internal/domain/entities"
	"github.com/VeRJiL/go-template/internal/pkg/modules"
)

// ProductService defines the interface for product service
type ProductService interface {
	modules.Service[entities.Product]

	// Add custom service methods here
	FindByName(ctx context.Context, name string) (*entities.Product, error)
	SearchByName(ctx context.Context, pattern string) ([]*entities.Product, error)
	ValidateName(ctx context.Context, name string) error
}
